### PR TITLE
Api fix

### PR DESCRIPTION
**Pull request by LLazarek**
Moved api code into src and include directories, also added README on using the api in a doc folder.

### CODE REVIEW

**Comment by djbaumann** [comment]
hey I couldnt get the current CMakeLists.txt to work, I had to change line 10 to:

```C++
include_directories(include include/api)
```

to make it work. Would you be able to change that?

**Comment by djbaumann** [comment]
Looks great but I can't merge it in. I guess I need Jake or Josh to review it first because I don't have admin access

**Review by jacobhempel — APPROVED** [review]
Baumann I'm trusting you :octopus: 

EDIT: Looks like Josh needs to approve it too? It says I'm an admin on the repo but I approved it and it says merging is still blocked.

**Comment by DarrienG** [comment]
Ironically I'm not an admin. Josh, where you at?

**Comment by JoshuaHassler** [comment]
Go to Files Changed. Click on the Review Changes Dropdown. Select Approve (if your intent is to approve this) add your comment then submit review. Anyone can do this and it will pass the review required check, then anyone can merge! I'll add some workflow to the wiki!

**Review by JoshuaHassler — APPROVED** [review]
All reviewers do need to approve (but you could just remove me as a reviewer). Changes look good! 🐙

**Pull request merged**
