### PR TITLE
Cdh api dev

### PR DESCRIPTION
**Pull request by LLazarek**

### CODE REVIEW

**Comment by DarrienG** [comment]
I've looked at it a bit, and I really like how it looks! 

Two comments:

In mediator_compiles.cpp, there's a long explanation about pros and cons of our solution. Code isn't the place for this. If we want to create a wiki page, or a separate doc, we can do that! 

There are a lot of commits here, they need to be squashed before they can be accepted. Check out the "[After you've finished development](https://tree.taiga.io/project/darrieng-command-and-data-handling/wiki/workflow )" section in the wiki, and make sure to squash your commits.

**Comment by DarrienG** [comment]
I'm going to request that at least one other person look over the code too just to make sure I didn't miss anything. @MikeZurawski up for the challenge? 😉

**Comment by LLazarek** [comment]
I can just get rid of mediator_compiles.cpp. I only have it there in case anyone wanted to verify that this crazy stuff actually compiles.

**Comment by MikeZurawski** [comment]
Only thing I think it needs is a couple more comments here and there.

But other than that it looks great!

**Comment by DarrienG** [comment]
It's alright to leave mediator_compiles in there, it's a good example, but it should be cleaned up. If you wanted to just remove it, that works too.

**Comment by JoshuaHassler** [comment]
You have in one of your comments that something does not pass linting, is that still true?

**Comment by LLazarek** [comment]
Made all requested changes.

**Comment by DarrienG** [comment]
This is great! However, I'm holding off on the merge right now. An in person review review (for questions and such) has been requested. We should wait until the next meeting, and I will likely merge it after that.

**Pull request merged**
