### PR TITLE
CHANGELOG:

### PR DESCRIPTION
**Pull request by DarrienG**
```
Feature: #95
    Create initial code skeleton.
```

This is the most basic a code skeleton can get, and yet it should be enough to get started.

### CODE REVIEW

**Comment by DarrienG** [comment]
Please look over what I've done so far. If there are any objections, do tell so I can fix them.

**Comment by SPKB24** [comment]
It's very Arduino-esque. It looks good. What is meant by production vs non-production?

**Comment by DarrienG** [comment]
That was the intent. We talked about this on back-end, and we weren't super certain where to start, or if we even needed a notion of "tiers" so we just said screw it, let's make it like an Arduino for now. 

As for ISPRODUCTION. That's outside of the scope of the story. It should be removed. I'll get rid of it when I get the chance. I got a little too ahead of myself.

**Comment by DarrienG** [comment]
There don't seem to be any objections to the code, and it is basic stuff. I'm going to go ahead and merge.

**Pull request merged**
